# Generated by Django 5.2.5 on 2025-09-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Optional: A screenshot of your project.', null=True, upload_to='project_images/')),
                ('technologies', models.CharField(help_text='E.g., Django, React, PostgreSQL', max_length=200)),
                ('project_url', models.URLField(blank=True, help_text='Optional: The URL where the project is live.', null=True, verbose_name='Project URL')),
                ('github_url', models.URLField(blank=True, help_text='Optional: The URL to the source code on GitHub.', null=True, verbose_name='GitHub URL')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Projects with lower numbers are displayed first.')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
